spring:
    application:
        name: user_service
    datasource:
        url: jdbc:postgresql://localhost:5432/user_news_db
        username: postgres
        password: root
    jpa:
        hibernate:
            ddl-auto: update
server:
    port: 8000