spring:
    application:
        name: comment_service
    datasource:
        url: jdbc:postgresql://localhost:5432/comment_news_db
        username: postgres
        password: root
    jpa:
        hibernate:
            ddl-auto: update
server:
    port: 7000
